version: "2.1"
orbs:
  heroku: circleci/heroku@2.0

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt  # Ensure you have a requirements.txt
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - deploy
