version: "2.1"
orbs:
  heroku: circleci/heroku@2.0

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt  # Install requirements without virtualenv
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - deploy

run:
  name: Set up Heroku credentials
  command: echo HRKU-9e0226fc-428e-47b8-8447-1b309bf46ac9 | docker login --username=_ --password-stdin registry.heroku.com
