version: 2.1

orbs:
  heroku: circleci/heroku@2.0

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: "pythonservice"
          pre-steps:
            - run:
                name: Run pre-deployment commands
                command: |
                  echo "Pre-deployment steps"
                  # Add any commands you want to run before deployment, e.g. tests
          post-steps:
            - run:
                name: Run database migrations
                command: |
                  heroku run python manage.py migrate --app pythonservice
                  # Replace with any post-deployment steps you need, like database migrations
